import React from "react"
import type { NextPage } from "next"
import Head from "next/head"
import { Container } from "../components/container"

const Home: NextPage = () => {
  const [notepadOpen, setNotepadOpen] = React.useState(false)

  return (
    <>
      <Head>
        <title>React TypeScript Components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <h1 className=" text-green font-mono ">TEST</h1>
      </Container>
    </>
  )
}

export default Home
